id: I38F919C0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T12:00:52+00:00'
last_modified: '2022-06-10T10:06:53.901904+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN5072
  title: རི་ཡི་ཆོས་གཏམ་ཀུན་བཟང་པོའི་སྒྲ་དབྱངས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    F4B5:
      image_group_id: I3CN5074
      title: Volume 1 of ri yi chos gtam kun bzang po'i sgra dbyangs/
      total_pages: 120
      order: 1
      base_file: F4B5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
