id: P000569
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-16 15:47:30.006625
source_metadata:
  id: bdr:W3CN5072
  title: རི་ཡི་ཆོས་གཏམ་ཀུན་བཟང་པོའི་སྒྲ་དབྱངས།
  author: ''
  volumes:
    04ba093364494626a5e533d0ad32146d:
      image_group_id: I3CN5074
      title: Volume 1 of ri yi chos gtam kun bzang po'i sgra dbyangs/
      volume_number: 1
      total_pages: 120
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
